### ISSUE TITLE
Mover has a ghost vehicle [1.20.1]

### ISSUE THREAD

**Issue by TheDarkPreacher** [McJtyMods/RFToolsBuilder#117] opened 2023-07-20 15:02 UTC
version: RftoolsBuilder 1.20-6.0.0

Forge version: 47.1.33

Issue: After creating a vehicle card for the mover and placing it in a mover block, there is a weird ghost vehicle that seems like a preview.

![2023-07-20_09 57 37](https://github.com/McJtyMods/RFToolsBuilder/assets/15058826/0f8ea09b-ea89-4b92-970a-1a47427c2b25)

**Comment by MCcodeXX** [comment] 2023-08-09 01:22
Yes, I have experienced the same thing in my 1.20.1 world and was looking for answers. This together with the fact that it is not possible to scan for other movers (the scan button only detects the mover in the system that touches the controller) makes this lift system quite useless at the moment. Too bad as I was looking forward to using it as a tour of my base.

**Comment by McJty** [comment] 2023-08-09 04:57
The scan button detects the mover that touches the controller and ALL other movers that are in a straight line directly from that mover (in all six directions)

**Comment by McJty** [comment] 2023-08-09 04:58
Also that ghost vehicle is intended. That's the platform on which you will move around. Not sure what the problem here is exactly

**Comment by McJty** [comment] 2023-08-09 04:59
For @TheDarkPreacher

**Comment by TheDarkPreacher** [comment] 2023-08-09 07:40
In my screenshot, the mover that has been placed, built with the card in the mover block, is on the right. The "preview" persists as long as the card is in the mover block, and follows you everywhere.  It gets worse the closer to the vehicle you get, to the point where you are inside the vehicle and can't see anything because the "preview" is covering the vehicle. This is after you hit "Scan" in the mover controller. The "preview" goes away when you take the vehicle card from the mover. Here is a screenshot where the vehicle is stationary on the ground, and the "preview" is up in the air.
![image](https://github.com/McJtyMods/RFToolsBuilder/assets/15058826/6c210d6d-9296-4f32-b4f2-db55db7ddf97)

**Comment by MCcodeXX** [comment] 2023-08-09 08:09
Hi McJty. Thank you for taking the time to clarify this even though I brought it up in a thread that was not related to the matter. There was no documentation of this in the game. I made the guide but couldn't open it.

TheDarkPreacher: Didn't mean to hijack your thread, just trying to reactivate it so McJty would be aware. And yes, hope McJty sees that the "preview" is NOT the moving platform, but is tied to the mouse pointer.

Have a wonderful day both of you!

**Comment by McJty** [comment] 2023-08-10 04:11
Ok. I can reproduce the ghost problem

**Comment by TheDarkPreacher** [comment] 2023-08-10 05:00
Awesome, hope you're able to track down the bug.

**Comment by McJty** [comment] 2023-08-10 05:01
The bug is fixed with the latest release of McJtyLib that I just pushed. The other bug mentioned in this ticket I cannot reproduce. The mover is working fine as far as I know

**Closed as completed by McJty** 2023-08-10 05:01 UTC
