### ISSUE TITLE
[1.15.2] Game crash when accessing Shape card config in builder

### ISSUE THREAD

**Issue by florian-berger** [McJtyMods/RFToolsBuilder#18] opened 2020-05-16 14:41 UTC
**Issue description:** 
When I open the GUI of the builder and click the button beside the shape card to open its configuration, the game crashes.

**Steps to reproduce:** 
1. Place Builder
2. Configure shape card (cleaning quarry) and insert into Builder
3. Click button beside the shape card for configuration

**Versions:**
* Minecraft: 1.15.2
* Forge: 31.1.63
* McJtyLib: 4.1.0-beta
* RFTools Base: 1.1.1-beta
* RFTools Builder: 2.1.1-beta

**Possibly incompatible mods and versions:** 

**Relevant logs, if any:** 
[crash-2020-05-16_16.25.30-client.txt](https://github.com/McJtyMods/RFToolsBuilder/files/4638544/crash-2020-05-16_16.25.30-client.txt)

**Comment by McJty** [comment] 2020-05-16 17:25
Hmm I cannot reproduce this and I also can't see a reason for this crash. Very weird. Does this happen every time for you?

**Comment by florian-berger** [comment] 2020-05-16 19:41
Yes, the games crashes every time I use that button:
![image](https://user-images.githubusercontent.com/10084586/82128710-61952980-97bd-11ea-9cd3-b26499e21abe.png)

In the meantime, I was able to find out that the UI can be opened by right-clicking when holding the card in my main hand.

**Comment by McJty** [comment] 2020-05-16 20:48
Very weird. Works fine for me. I cannot reproduce this at all

**Comment by LuciusV** [comment] 2020-05-20 10:21
Same crash there. There is my crash log:
[crash-2020-05-20_18.18.40-client.txt](https://github.com/McJtyMods/RFToolsBuilder/files/4656141/crash-2020-05-20_18.18.40-client.txt)

**Comment by LatvianModder** [comment] 2020-05-21 11:13
Ive seen this issue couple times auto-reported. Here's two different stacks:

https://mcmc.dev/crashes/client/G_M5cjbtayob
https://mcmc.dev/crashes/client/JRs5ci__eAAl

**Comment by McJty** [comment] 2020-05-23 08:31
I worked around the bug. This will be fixed next release

**Closed as completed by McJty** 2020-05-23 08:31 UTC
